// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FilterItems(arg1:string):Promise<Array<main.ListItem>>;

export function GetApplications():Promise<void>;

export function GetProcesses():Promise<void>;

export function HideWindow():Promise<void>;

export function SelectItem(arg1:number):Promise<void>;

export function ShowWindow():Promise<void>;
