// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterItems(arg1) {
  return window['go']['main']['App']['FilterItems'](arg1);
}

export function GetApplications() {
  return window['go']['main']['App']['GetApplications']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SelectItem(arg1) {
  return window['go']['main']['App']['SelectItem'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
